import { useState } from 'react'
import './HealthProvider.css'

export default function HealthProvider() {
  const [formData, setFormData] = useState({
    testDate: '',
    radonLevels: '',
    exposureDuration: '',
    basementIsSleepingArea: false,
    lastConstructionRepair: '',
    symptoms: '',
    concerns: '',
    additionalNotes: '',
  })

  const [generatedNote, setGeneratedNote] = useState<string | null>(null)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const target = e.target
    const value = target.type === 'checkbox' ? (target as HTMLInputElement).checked : target.value
    const name = target.name
    
    setFormData({
      ...formData,
      [name]: value,
    })
  }

  const generateNote = () => {
    const note = `RADON EXPOSURE CONSULTATION REQUEST

Radon Exposure Details:
----------------------
Test Date: ${formData.testDate}
Radon Levels: ${formData.radonLevels} pCi/L
Exposure Duration: ${formData.exposureDuration}

Home Information:
-----------------
Basement is a sleeping area: ${formData.basementIsSleepingArea ? 'Yes' : 'No'}
Last construction project, flood, or major foundation repair: ${formData.lastConstructionRepair || 'None reported'}

Symptoms:
---------
${formData.symptoms || 'None reported'}

Concerns:
---------
${formData.concerns || 'None specified'}

Additional Notes:
----------------
${formData.additionalNotes || 'None'}

Request:
--------
I am requesting a consultation to discuss potential health risks associated with radon exposure in my home. The Environmental Protection Agency (EPA) recommends action when radon levels exceed 4.0 pCi/L. I would like to discuss:

1. Health risks associated with the measured radon levels
2. Recommended medical monitoring or screening
3. Symptoms that may be related to radon exposure
4. Any preventive measures or treatment options

I would appreciate your guidance on whether any additional health screenings or monitoring would be appropriate given my exposure history.

Thank you for your attention to this matter.

Date: ${new Date().toLocaleDateString()}

---
Note: This form was generated by the Radon Canvas App for informational purposes.
Please consult with your healthcare provider for medical advice.`

    setGeneratedNote(note)
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    generateNote()
  }

  const copyToClipboard = () => {
    if (generatedNote) {
      navigator.clipboard.writeText(generatedNote)
      alert('Note copied to clipboard!')
    }
  }

  const downloadAsFile = () => {
    if (generatedNote) {
      const blob = new Blob([generatedNote], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `radon-consultation-request-${new Date().toISOString().split('T')[0]}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
  }

  const resetForm = () => {
    setFormData({
      testDate: '',
      radonLevels: '',
      exposureDuration: '',
      basementIsSleepingArea: false,
      lastConstructionRepair: '',
      symptoms: '',
      concerns: '',
      additionalNotes: '',
    })
    setGeneratedNote(null)
  }

  return (
    <div>
      <div className="card">
        <div className="card-header">
          <h2 className="card-title">💉 Health Provider Resources</h2>
        </div>
        <p style={{ color: '#666', marginBottom: '2rem', fontSize: '1.1rem' }}>
          Use this form to generate a professional note to share with your healthcare provider about
          radon exposure concerns. Fill out the form and generate a formatted consultation request
          that you can print, email, or share with your provider.
        </p>

        {!generatedNote ? (
          <form onSubmit={handleSubmit} className="health-provider-form">
            <div className="form-section">
              <h3 className="form-section-title">Radon Exposure Details</h3>
              <div className="form-grid">
                <div className="form-group">
                  <label className="form-label">Test Date</label>
                  <input
                    type="date"
                    className="form-input"
                    name="testDate"
                    value={formData.testDate}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Radon Levels (pCi/L)</label>
                  <input
                    type="text"
                    className="form-input"
                    name="radonLevels"
                    value={formData.radonLevels}
                    onChange={handleChange}
                    placeholder="e.g., 5.2"
                  />
                  <small style={{ color: '#666', display: 'block', marginTop: '0.5rem' }}>
                    EPA action level: 4.0 pCi/L
                  </small>
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Exposure Duration</label>
                <input
                  type="text"
                  className="form-input"
                  name="exposureDuration"
                  value={formData.exposureDuration}
                  onChange={handleChange}
                  placeholder="e.g., 2 years, 6 months"
                />
              </div>
            </div>

            <div className="form-section">
              <h3 className="form-section-title">Home Information</h3>
              <div className="form-group">
                <label className="checkbox-label" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', cursor: 'pointer' }}>
                  <input
                    type="checkbox"
                    name="basementIsSleepingArea"
                    checked={formData.basementIsSleepingArea}
                    onChange={handleChange}
                    style={{ width: '20px', height: '20px', cursor: 'pointer' }}
                  />
                  <span className="form-label" style={{ margin: 0 }}>
                    Is the basement a sleeping area?
                  </span>
                </label>
                <small style={{ color: '#666', display: 'block', marginTop: '0.5rem', marginLeft: '2rem' }}>
                  If bedrooms or sleeping spaces are located in the basement, this may affect exposure levels.
                </small>
              </div>
              <div className="form-group">
                <label className="form-label">
                  When was the last construction project, flood, or major foundation repair?
                </label>
                <input
                  type="text"
                  className="form-input"
                  name="lastConstructionRepair"
                  value={formData.lastConstructionRepair}
                  onChange={handleChange}
                  placeholder="e.g., January 2020, Spring 2018, Never"
                />
                <small style={{ color: '#666', display: 'block', marginTop: '0.5rem' }}>
                  Recent construction or foundation work may have affected radon entry points in your home.
                </small>
              </div>
            </div>

            <div className="form-section">
              <h3 className="form-section-title">Health Information</h3>
              <div className="form-group">
                <label className="form-label">Symptoms (if any)</label>
                <textarea
                  className="form-textarea"
                  name="symptoms"
                  value={formData.symptoms}
                  onChange={handleChange}
                  placeholder="Describe any symptoms you may be experiencing..."
                  rows={4}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Concerns</label>
                <textarea
                  className="form-textarea"
                  name="concerns"
                  value={formData.concerns}
                  onChange={handleChange}
                  placeholder="Describe your concerns about radon exposure..."
                  rows={4}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Additional Notes</label>
                <textarea
                  className="form-textarea"
                  name="additionalNotes"
                  value={formData.additionalNotes}
                  onChange={handleChange}
                  placeholder="Any additional information you'd like to include..."
                  rows={3}
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end', marginTop: '2rem' }}>
              <button type="button" className="btn btn-secondary" onClick={resetForm}>
                Reset Form
              </button>
              <button type="submit" className="btn btn-primary">
                Generate Note
              </button>
            </div>
          </form>
        ) : (
          <div className="generated-note-container">
            <div className="generated-note-header">
              <h3>Generated Consultation Request</h3>
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <button className="btn btn-secondary btn-sm" onClick={copyToClipboard}>
                  📋 Copy to Clipboard
                </button>
                <button className="btn btn-secondary btn-sm" onClick={downloadAsFile}>
                  💾 Download as File
                </button>
                <button className="btn btn-secondary btn-sm" onClick={resetForm}>
                  ✏️ Edit Form
                </button>
              </div>
            </div>
            <div className="generated-note-content">
              <pre>{generatedNote}</pre>
            </div>
            <div style={{ marginTop: '1rem', padding: '1rem', background: '#f3f4f6', borderRadius: '8px' }}>
              <h4 style={{ marginBottom: '0.5rem' }}>Next Steps:</h4>
              <ul style={{ margin: 0, paddingLeft: '1.5rem', color: '#666' }}>
                <li>Copy the note above or download it as a text file</li>
                <li>Email it to your healthcare provider or print it to bring to your appointment</li>
                <li>Call your provider's office to schedule a consultation</li>
                <li>Bring a copy of your radon test results to your appointment</li>
              </ul>
            </div>
          </div>
        )}
      </div>

      <div className="card">
        <div className="info-box">
          <h3>ℹ️ Important Information</h3>
          <ul>
            <li>
              <strong>EPA Recommendations:</strong> The EPA recommends taking action when radon
              levels exceed 4.0 pCi/L. Consider action between 2.0-4.0 pCi/L.
            </li>
            <li>
              <strong>Health Risks:</strong> Radon is the second leading cause of lung cancer after
              smoking. Long-term exposure to elevated radon levels increases your risk of lung
              cancer.
            </li>
            <li>
              <strong>Consultation:</strong> If you have concerns about radon exposure, consult with
              your healthcare provider. They can help assess your risk and recommend appropriate
              screening or monitoring.
            </li>
            <li>
              <strong>Documentation:</strong> Keep records of your radon test results and any
              correspondence with your healthcare provider regarding radon exposure.
            </li>
            <li>
              <strong>Disclaimer:</strong> This form is for informational purposes only and does not
              constitute medical advice. Always consult with a qualified healthcare provider for
              medical concerns.
            </li>
          </ul>
        </div>
      </div>
    </div>
  )
}
